version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    container_name: w8box-watcher-01
    environment:
      - TZ=Europe/Moscow
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - ./data:/data

networks:
  node-red-net:
