version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    container_name: w8box-watcher-01
    network_mode: host
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./data:/data
